//! VFIO configuration management
//!
//! This module handles persistent VFIO configuration including:
//! - modprobe.d configuration for vfio-pci driver
//! - Initramfs configuration (mkinitcpio, dracut, update-initramfs)
//! - Kernel parameter recommendations

use super::errors::VfioError;
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;
use std::process::Command;

/// Detected initramfs system
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum InitramfsSystem {
    /// Arch Linux mkinitcpio
    Mkinitcpio,
    /// Fedora/RHEL dracut
    Dracut,
    /// Debian/Ubuntu update-initramfs
    UpdateInitramfs,
    /// Unknown system
    Unknown,
}

impl std::fmt::Display for InitramfsSystem {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            InitramfsSystem::Mkinitcpio => write!(f, "mkinitcpio (Arch Linux)"),
            InitramfsSystem::Dracut => write!(f, "dracut (Fedora/RHEL)"),
            InitramfsSystem::UpdateInitramfs => write!(f, "update-initramfs (Debian/Ubuntu)"),
            InitramfsSystem::Unknown => write!(f, "Unknown"),
        }
    }
}

/// VFIO configuration for a device
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VfioDeviceConfig {
    /// PCI address (e.g., "0000:01:00.0")
    pub pci_address: String,
    /// Vendor ID (e.g., "10de")
    pub vendor_id: String,
    /// Device ID (e.g., "2684")
    pub device_id: String,
    /// Human-readable description
    pub description: String,
}

/// Complete VFIO configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VfioConfig {
    /// Devices to bind to vfio-pci at boot
    pub devices: Vec<VfioDeviceConfig>,
    /// Whether to enable IOMMU unsafe interrupts
    pub unsafe_interrupts: bool,
    /// Whether to enable ACS override
    pub acs_override: bool,
}

impl Default for VfioConfig {
    fn default() -> Self {
        Self {
            devices: Vec::new(),
            unsafe_interrupts: false,
            acs_override: false,
        }
    }
}

/// Detect which initramfs system is in use
pub fn detect_initramfs_system() -> InitramfsSystem {
    // Check for mkinitcpio (Arch Linux)
    if Path::new("/etc/mkinitcpio.conf").exists() {
        return InitramfsSystem::Mkinitcpio;
    }

    // Check for dracut (Fedora, RHEL, openSUSE)
    if Path::new("/etc/dracut.conf").exists() || Path::new("/etc/dracut.conf.d").exists() {
        return InitramfsSystem::Dracut;
    }

    // Check for update-initramfs (Debian, Ubuntu)
    if Path::new("/etc/initramfs-tools").exists() {
        return InitramfsSystem::UpdateInitramfs;
    }

    InitramfsSystem::Unknown
}

/// Generate modprobe.d configuration content
pub fn generate_modprobe_config(config: &VfioConfig) -> String {
    let mut lines = Vec::new();

    lines.push("# VFIO configuration generated by ghostctl".to_string());
    lines.push("# Device IDs for vfio-pci to claim at boot".to_string());
    lines.push("".to_string());

    if !config.devices.is_empty() {
        // Collect unique vendor:device IDs
        let ids: Vec<String> = config
            .devices
            .iter()
            .map(|d| format!("{}:{}", d.vendor_id, d.device_id))
            .collect();

        lines.push(format!("options vfio-pci ids={}", ids.join(",")));
    }

    // Softdep to load vfio-pci before GPU drivers
    lines.push("".to_string());
    lines.push("# Ensure vfio-pci loads before GPU drivers".to_string());
    lines.push("softdep nvidia pre: vfio-pci".to_string());
    lines.push("softdep amdgpu pre: vfio-pci".to_string());
    lines.push("softdep radeon pre: vfio-pci".to_string());
    lines.push("softdep nouveau pre: vfio-pci".to_string());
    lines.push("softdep i915 pre: vfio-pci".to_string());

    if config.unsafe_interrupts {
        lines.push("".to_string());
        lines.push("# Allow unsafe interrupts (may be needed for some systems)".to_string());
        lines.push("options vfio_iommu_type1 allow_unsafe_interrupts=1".to_string());
    }

    lines.join("\n")
}

/// Write modprobe.d configuration
pub fn write_modprobe_config(config: &VfioConfig) -> Result<()> {
    let content = generate_modprobe_config(config);
    let path = "/etc/modprobe.d/vfio.conf";

    fs::write(path, &content)
        .with_context(|| format!("Failed to write {}. Try running as root (sudo).", path))?;

    println!("Written: {}", path);
    Ok(())
}

/// Generate mkinitcpio.conf hooks modification
pub fn generate_mkinitcpio_hooks() -> &'static str {
    "# Add these modules to MODULES array in /etc/mkinitcpio.conf:
# MODULES=(... vfio_pci vfio vfio_iommu_type1 ...)
#
# Then regenerate initramfs:
# sudo mkinitcpio -P"
}

/// Generate dracut configuration
pub fn generate_dracut_config() -> String {
    r#"# VFIO configuration for dracut
# Place in /etc/dracut.conf.d/vfio.conf

add_drivers+=" vfio vfio_iommu_type1 vfio_pci "
"#
    .to_string()
}

/// Generate initramfs-tools configuration
pub fn generate_initramfs_tools_config() -> String {
    r#"# VFIO modules for initramfs-tools
# Place in /etc/initramfs-tools/modules

vfio
vfio_iommu_type1
vfio_pci
"#
    .to_string()
}

/// Write initramfs configuration based on detected system
pub fn write_initramfs_config(system: InitramfsSystem) -> Result<()> {
    match system {
        InitramfsSystem::Mkinitcpio => {
            println!("\nFor mkinitcpio (Arch Linux):");
            println!("{}", generate_mkinitcpio_hooks());
            println!("\nNote: Manual edit required for mkinitcpio.conf");
        }
        InitramfsSystem::Dracut => {
            let content = generate_dracut_config();
            let path = "/etc/dracut.conf.d/vfio.conf";

            fs::write(path, &content).with_context(|| {
                format!("Failed to write {}. Try running as root (sudo).", path)
            })?;

            println!("Written: {}", path);
            println!("\nRegenerate initramfs with: sudo dracut -f");
        }
        InitramfsSystem::UpdateInitramfs => {
            let content = generate_initramfs_tools_config();
            let path = "/etc/initramfs-tools/modules";

            // Append to existing file or create new
            let existing = fs::read_to_string(path).unwrap_or_default();
            if !existing.contains("vfio_pci") {
                let new_content = format!("{}\n{}", existing.trim(), content);
                fs::write(path, new_content).with_context(|| {
                    format!("Failed to write {}. Try running as root (sudo).", path)
                })?;
                println!("Updated: {}", path);
            } else {
                println!("VFIO modules already present in {}", path);
            }

            println!("\nRegenerate initramfs with: sudo update-initramfs -u");
        }
        InitramfsSystem::Unknown => {
            println!("\nUnknown initramfs system. Manual configuration required.");
            println!("Ensure these modules are loaded early:");
            println!("  - vfio");
            println!("  - vfio_iommu_type1");
            println!("  - vfio_pci");
        }
    }

    Ok(())
}

/// Regenerate initramfs
pub fn regenerate_initramfs(system: InitramfsSystem) -> Result<()> {
    let (cmd, args): (&str, &[&str]) = match system {
        InitramfsSystem::Mkinitcpio => ("mkinitcpio", &["-P"]),
        InitramfsSystem::Dracut => ("dracut", &["-f"]),
        InitramfsSystem::UpdateInitramfs => ("update-initramfs", &["-u"]),
        InitramfsSystem::Unknown => {
            return Err(VfioError::ConfigError {
                path: "initramfs".to_string(),
                reason: "Unknown initramfs system".to_string(),
            }
            .into());
        }
    };

    println!("Regenerating initramfs with: {} {}", cmd, args.join(" "));

    let status = Command::new(cmd)
        .args(args)
        .status()
        .with_context(|| format!("Failed to run {}", cmd))?;

    if !status.success() {
        return Err(VfioError::ConfigError {
            path: "initramfs".to_string(),
            reason: format!("{} failed with exit code {:?}", cmd, status.code()),
        }
        .into());
    }

    println!("Initramfs regenerated successfully.");
    Ok(())
}

/// Get recommended kernel parameters
pub fn get_kernel_params_recommendation() -> String {
    let cpu_vendor = detect_cpu_vendor();

    let iommu_param = match cpu_vendor.as_str() {
        "Intel" => "intel_iommu=on",
        "AMD" => "amd_iommu=on",
        _ => "intel_iommu=on (or amd_iommu=on)",
    };

    format!(
        r#"Recommended kernel parameters:

  {} iommu=pt

Add these to your bootloader configuration:
  - GRUB: /etc/default/grub (GRUB_CMDLINE_LINUX_DEFAULT)
  - systemd-boot: /boot/loader/entries/*.conf
  - rEFInd: /boot/refind_linux.conf

After updating, regenerate bootloader config:
  - GRUB: sudo grub-mkconfig -o /boot/grub/grub.cfg
  - systemd-boot: No regeneration needed
  - rEFInd: No regeneration needed
"#,
        iommu_param
    )
}

/// Detect CPU vendor
fn detect_cpu_vendor() -> String {
    if let Ok(cpuinfo) = fs::read_to_string("/proc/cpuinfo") {
        if cpuinfo.contains("GenuineIntel") {
            return "Intel".to_string();
        } else if cpuinfo.contains("AuthenticAMD") {
            return "AMD".to_string();
        }
    }
    "Unknown".to_string()
}

/// Check if VFIO configuration exists
pub fn check_existing_config() -> VfioConfigStatus {
    let modprobe_exists = Path::new("/etc/modprobe.d/vfio.conf").exists();
    let system = detect_initramfs_system();

    let initramfs_configured = match system {
        InitramfsSystem::Mkinitcpio => {
            if let Ok(content) = fs::read_to_string("/etc/mkinitcpio.conf") {
                content.contains("vfio_pci")
            } else {
                false
            }
        }
        InitramfsSystem::Dracut => Path::new("/etc/dracut.conf.d/vfio.conf").exists(),
        InitramfsSystem::UpdateInitramfs => {
            if let Ok(content) = fs::read_to_string("/etc/initramfs-tools/modules") {
                content.contains("vfio_pci")
            } else {
                false
            }
        }
        InitramfsSystem::Unknown => false,
    };

    VfioConfigStatus {
        modprobe_configured: modprobe_exists,
        initramfs_configured,
        initramfs_system: system,
    }
}

/// Status of VFIO configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VfioConfigStatus {
    /// Whether modprobe.d/vfio.conf exists
    pub modprobe_configured: bool,
    /// Whether initramfs is configured for VFIO
    pub initramfs_configured: bool,
    /// Detected initramfs system
    pub initramfs_system: InitramfsSystem,
}

/// Print VFIO configuration status
pub fn print_config_status() {
    let status = check_existing_config();

    println!("\nVFIO Configuration Status");
    println!("{}", "=".repeat(50));

    println!(
        "\nmodprobe.d/vfio.conf:  {}",
        if status.modprobe_configured {
            "Configured"
        } else {
            "Not configured"
        }
    );

    println!("Initramfs system:      {}", status.initramfs_system);
    println!(
        "Initramfs configured:  {}",
        if status.initramfs_configured {
            "Yes"
        } else {
            "No"
        }
    );

    if status.modprobe_configured {
        if let Ok(content) = fs::read_to_string("/etc/modprobe.d/vfio.conf") {
            println!("\nCurrent modprobe.d/vfio.conf:");
            for line in content.lines() {
                if !line.trim().is_empty() && !line.starts_with('#') {
                    println!("  {}", line);
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_modprobe_config() {
        let config = VfioConfig {
            devices: vec![VfioDeviceConfig {
                pci_address: "0000:01:00.0".to_string(),
                vendor_id: "10de".to_string(),
                device_id: "2684".to_string(),
                description: "NVIDIA RTX 5090".to_string(),
            }],
            unsafe_interrupts: false,
            acs_override: false,
        };

        let output = generate_modprobe_config(&config);
        assert!(output.contains("options vfio-pci ids=10de:2684"));
        assert!(output.contains("softdep nvidia pre: vfio-pci"));
    }

    #[test]
    fn test_generate_modprobe_config_multiple_devices() {
        let config = VfioConfig {
            devices: vec![
                VfioDeviceConfig {
                    pci_address: "0000:01:00.0".to_string(),
                    vendor_id: "10de".to_string(),
                    device_id: "2684".to_string(),
                    description: "GPU".to_string(),
                },
                VfioDeviceConfig {
                    pci_address: "0000:01:00.1".to_string(),
                    vendor_id: "10de".to_string(),
                    device_id: "22bc".to_string(),
                    description: "Audio".to_string(),
                },
            ],
            unsafe_interrupts: true,
            acs_override: false,
        };

        let output = generate_modprobe_config(&config);
        assert!(output.contains("ids=10de:2684,10de:22bc"));
        assert!(output.contains("allow_unsafe_interrupts=1"));
    }

    #[test]
    fn test_generate_dracut_config() {
        let output = generate_dracut_config();
        assert!(output.contains("vfio_pci"));
        assert!(output.contains("vfio_iommu_type1"));
    }
}
