name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    name: Build on ghost-nv
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose
        working-directory: ./ghostctl

      - name: Test
        run: cargo test --verbose
        working-directory: ./ghostctl
